name: Contents Read Example

on: [push]

permissions:
  contents: read

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo        /*bu adım, repo içeriğini kontrol eder ve çalışma alanına indirir*/
        uses: actions/checkout@v4   /*checkout işlemi için actions/checkout@v4 kullanılır*/
      - name: Show repo files       /*bu adım, repo içeriğini gösterir*/
        run: ls -la                 /*ls -la komutu ile repo içeriği listelenir*/
