name: Commit Durum Kontrolcüsü

on:
  pull_request:
    branches: [ "main" ]

permissions:
  statuses: write # Commit durumunu güncelleme izni
  contents: read  # Depo içeriğini okumak (checkout) için gerekli

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Depo kodunu indir (Checkout)
        uses: actions/checkout@v4

      - name: Durumu 'beklemede' olarak ayarla
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'pending',
              description: 'Kalite kontrolleri çalışıyor...',
              context: 'Kalite Kontrolü'
            })

      - name: Kalite kontrolünü çalıştır (Simülasyon)
        run: echo "Kod kalitesi kontrol ediliyor... Her şey yolunda!"

      - name: Başarılı durumu bildir
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'success',
              description: 'Kontroller başarıyla tamamlandı!',
              context: 'Kalite Kontrolü'
            })

      - name: Hata durumunu bildir
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'failure',
              description: 'Kontroller başarısız oldu.',
              context: 'Kalite Kontrolü'
            })

